#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_posbundle:
  resource: '@FlexyPOSBundle/Resources/config/routes.yaml'
  prefix: /pos/
_billards:
  resource: '@FlexyBillardsBundle/Resources/config/routes.yaml'
  prefix: /
_stock:
  resource: '@FlexyStockBundle/Resources/config/routes.yaml'
  prefix: /
_front:
  resource: '@FlexyFrontBundle/Resources/config/routes.yaml'
  prefix: /
_shop:
  resource: '@FlexyShopBundle/Resources/config/routes.yaml'
  prefix: /
